In [1]:
# Step 2.1: Import required libraries
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [3]:
# Step 2.2: Load Excel files safely

mdm_infra = pd.read_csv("../data/raw/meghalaya/health/MDM_Infra_Report.csv")
ifa_blue = pd.read_csv("../data/raw/meghalaya/health/ifa-Blue-tablet.csv")
ifa_pink = pd.read_csv("../data/raw/meghalaya/health/ifa-Pink-tablet.csv")
deworm = pd.read_csv("../data/raw/meghalaya/health/MDM_Deworming_Report.csv")

print("MDM Infra:", mdm_infra.shape)
print("IFA Blue:", ifa_blue.shape)
print("IFA Pink:", ifa_pink.shape)
print("Deworming:", deworm.shape)

MDM Infra: (396, 27)
IFA Blue: (64, 19)
IFA Pink: (39, 19)
Deworming: (49, 17)

In [4]:
# Step 2.3: Inspect columns

mdm_infra.columns

Index(['UDISE Code', 'School Name', 'Report Date', 'Timestamp',
       'Total Student Enrolment without Aadhaar',
       'Total Aadhaar Based Student Enrolment', 'Kitchen Sheds Available',
       'Conditions of Kitchen Sheds', 'Kitchen Device Available',
       'Conditions of Kitchen Device', 'Food Grain Available',
       'Food Grain Unavailable Reason', 'No of Cook Engaged',
       'Reason if cook not Available', 'Best Practices Adopted',
       'Name the Best Practices', 'Nutrition Kitchen Grade',
       'Types of Vegetables Grown', 'School Fencing Facilities',
       'Handwashing Facilities', 'Drinking Water Facilities',
       'Source of Water Facilities', 'Tithi Bhojan Celebrated',
       'If Yes, How Many Days', 'No. of Children Benefited',
       'Monthly School Introspection', 'Monthly School Inspection'],
      dtype='object')

In [5]:
ifa_blue.columns

Index(['district', 'block', 'cluster', 'udise', 'school', 'month',
       'reportingDate', 'timestamp', 'ifaGiven', 'reasonNo', 'noOfWeeks',
       'totalGirls', 'totalBoys', 'consuming4IfaGirls', 'consuming4IfaBoys',
       'ifaSideEffectGirls', 'ifaSideEffectBoys',
       'referredHealthFacilityGirls', 'referredHealthFacilityBoys'],
      dtype='object')

In [6]:
ifa_pink.columns

Index(['district', 'block', 'cluster', 'udise', 'school', 'month',
       'reportingDate', 'timestamp', 'ifaGiven', 'reasonNo', 'noOfWeeks',
       'totalGirls', 'totalBoys', 'consuming4IfaGirls', 'consuming4IfaBoys',
       'ifaSideEffectGirls', 'ifaSideEffectBoys',
       'referredHealthFacilityGirls', 'referredHealthFacilityBoys'],
      dtype='object')

In [7]:
deworm.columns

Index(['UDISE Code', 'School Name', 'Report Date', 'Timestamp',
       'Deworming tablets given (Yes/No)',
       'Total Student Enrolled (Class 1-5) Girls',
       'Total Student Enrolled (Class 1-5) Boys',
       'Total Student Enrolled (Class 6-12) Girls',
       'Total Student Enrolled (Class 6-12) Boys',
       'Total Students Administered Albendazole (Class 1-5) Girls',
       'Total Students Administered Albendazole (Class 1-5) Boys',
       'Total Students Administered Albendazole (Class 6-12) Girls',
       'Total Students Administered Albendazole (Class 6-12) Boys',
       'Students Experienced Side Effects (IFA) Girls',
       'Students Experienced Side Effects (IFA) Boys',
       'Students Referred to Health Facility Girls',
       'Students Referred to Health Facility Boys'],
      dtype='object')

In [8]:
mdm_clean = mdm_infra[[
    "UDISE Code",
    "School Name",
    "Kitchen Sheds Available",
    "Conditions of Kitchen Sheds",
    "Kitchen Device Available",
    "Conditions of Kitchen Device",
    "Food Grain Available",
    "No of Cook Engaged",
    "School Fencing Facilities",
    "Handwashing Facilities",
    "Drinking Water Facilities",
    "Total Student Enrolment without Aadhaar",
    "Total Aadhaar Based Student Enrolment"
]]

mdm_clean.columns = [
    "udise_code",
    "school_name",
    "kitchen_shed",
    "kitchen_shed_condition",
    "kitchen_device",
    "kitchen_device_condition",
    "food_grain",
    "no_of_cooks",
    "fencing",
    "handwash",
    "drinking_water",
    "students_without_aadhaar",
    "students_with_aadhaar"
]

mdm_clean.head()

,udise_code,school_name,kitchen_shed,kitchen_shed_condition,kitchen_device,kitchen_device_condition,food_grain,no_of_cooks,fencing,handwash,drinking_water,students_without_aadhaar,students_with_aadhaar
0,17010105501,BOLBOKGRE GOVT. LP SCHOOL,Yes,Good Condition,Yes,Good Condition,Yes,Yes,No,Yes,Yes,18.0,9.0
1,17110215701,BOLCHUGRE LPS,Yes,Need Minor Repair,Yes,Need Replacement,Yes,Yes,No,No,No,20.0,15.0
2,17010105401,BOLLONGGRE GOVT. LPS,Yes,Need Major Repair,Yes,Need Replacement,Yes,Yes,No,No,No,16.0,2.0
3,17110219602,BOLLONGGRE GOVT. LPS,Yes,Need Store Room,Yes,Good Condition,Yes,Yes,No,No,No,11.0,43.0
4,17110101001,CHIGITCHAKGRE GOVT. LPS,Yes,Need Major Repair,Yes,Need Replacement,Yes,Yes,NaN,NaN,NaN,9.0,13.0

In [9]:
ifa_blue_clean = ifa_blue[[
    "udise",
    "district",
    "block",
    "ifaGiven",
    "totalGirls",
    "totalBoys",
    "consuming4IfaGirls",
    "consuming4IfaBoys",
    "ifaSideEffectGirls",
    "ifaSideEffectBoys",
    "referredHealthFacilityGirls",
    "referredHealthFacilityBoys"
]]

ifa_blue_clean.columns = [
    "udise_code",
    "district_name",
    "block_name",
    "ifa_given",
    "total_girls",
    "total_boys",
    "consuming_girls",
    "consuming_boys",
    "side_effect_girls",
    "side_effect_boys",
    "referred_girls",
    "referred_boys"
]

ifa_blue_clean.head()

,udise_code,district_name,block_name,ifa_given,total_girls,total_boys,consuming_girls,consuming_boys,side_effect_girls,side_effect_boys,referred_girls,referred_boys
0,17080115101,NORTH GARO HILLS,BAJENGDOBA,Yes,0,0,0,0,0,0,0,0
1,17010206101,WEST GARO HILLS,DADENGGRE,Yes,8,7,0,0,8,7,0,0
2,17070100703,WEST JAINTIA HILLS,THADLASKEIN,Yes,3,1,0,0,3,1,0,0
3,17040403905,EASTERN WEST KHASI HILLS,MAWTHADRAISHAN,Yes,26,24,0,0,0,0,0,0
4,17040403910,EASTERN WEST KHASI HILLS,MAWTHADRAISHAN,Yes,45,54,0,0,0,0,0,0

In [10]:
ifa_pink_clean = ifa_pink[[
    "udise",
    "district",
    "block",
    "ifaGiven",
    "totalGirls",
    "totalBoys",
    "consuming4IfaGirls",
    "consuming4IfaBoys",
    "ifaSideEffectGirls",
    "ifaSideEffectBoys",
    "referredHealthFacilityGirls",
    "referredHealthFacilityBoys"
]]

ifa_pink_clean.columns = [
    "udise_code",
    "district_name",
    "block_name",
    "ifa_given",
    "total_girls",
    "total_boys",
    "consuming_girls",
    "consuming_boys",
    "side_effect_girls",
    "side_effect_boys",
    "referred_girls",
    "referred_boys"
]

ifa_pink_clean.head()

,udise_code,district_name,block_name,ifa_given,total_girls,total_boys,consuming_girls,consuming_boys,side_effect_girls,side_effect_boys,referred_girls,referred_boys
0,17080115101,NORTH GARO HILLS,BAJENGDOBA,Yes,0,0,0,0,0,0,0,0
1,17010206101,WEST GARO HILLS,DADENGGRE,Yes,12,15,0,0,12,15,0,021
2,17110108902,SOUTH WEST GARO HILLS,BETASING,Yes,12,13,12,13,12,13,7,8
3,17110221602,SOUTH WEST GARO HILLS,ZIKZAK,Yes,0,0,0,0,10,5,0,0
4,17040403905,EASTERN WEST KHASI HILLS,MAWTHADRAISHAN,Yes,34,45,0,0,0,0,0,0

In [11]:
deworm_clean = deworm[[
    "UDISE Code",
    "School Name",
    "Deworming tablets given (Yes/No)",
    "Total Student Enrolled (Class 1-5) Girls",
    "Total Student Enrolled (Class 1-5) Boys",
    "Total Students Administered Albendazole (Class 1-5) Girls",
    "Total Students Administered Albendazole (Class 1-5) Boys",
    "Students Experienced Side Effects (IFA) Girls",
    "Students Experienced Side Effects (IFA) Boys",
    "Students Referred to Health Facility Girls",
    "Students Referred to Health Facility Boys"
]]

deworm_clean.columns = [
    "udise_code",
    "school_name",
    "deworming_given",
    "enrolled_girls",
    "enrolled_boys",
    "treated_girls",
    "treated_boys",
    "side_effect_girls",
    "side_effect_boys",
    "referred_girls",
    "referred_boys"
]

deworm_clean.head()

,udise_code,school_name,deworming_given,enrolled_girls,enrolled_boys,treated_girls,treated_boys,side_effect_girls,side_effect_boys,referred_girls,referred_boys
0,17080115101,OMORPUR L.P.SCHOOL,Yes,21,23,21,23,NaN,NaN,NaN,NaN
1,17010206101,MAGALPARA LPS,Yes,22,19,22,19,NaN,NaN,NaN,NaN
2,17110204502,DASPARA GOVT. LPS,No,112,54,0,0,NaN,NaN,NaN,NaN
3,17110108902,JOYFAR LPS,Yes,12,13,12,13,NaN,NaN,NaN,NaN
4,17110221602,BARMANPARA NON-GOVT. LPS,Yes,10,5,10,5,NaN,NaN,NaN,NaN

In [12]:
# STEP 2.8: Merge MDM + IFA Blue + IFA Pink + Deworming using UDISE

school_health = mdm_clean.merge(ifa_blue_clean, on="udise_code", how="left", suffixes=("", "_ifa_blue"))
school_health = school_health.merge(ifa_pink_clean, on="udise_code", how="left", suffixes=("", "_ifa_pink"))
school_health = school_health.merge(deworm_clean, on="udise_code", how="left")

school_health.head()

,udise_code,school_name_x,kitchen_shed,kitchen_shed_condition,kitchen_device,kitchen_device_condition,food_grain,no_of_cooks,fencing,handwash,...,school_name_y,deworming_given,enrolled_girls,enrolled_boys,treated_girls,treated_boys,side_effect_girls_y,side_effect_boys_y,referred_girls_y,referred_boys_y
0,17010105501,BOLBOKGRE GOVT. LP SCHOOL,Yes,Good Condition,Yes,Good Condition,Yes,Yes,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17110215701,BOLCHUGRE LPS,Yes,Need Minor Repair,Yes,Need Replacement,Yes,Yes,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17010105401,BOLLONGGRE GOVT. LPS,Yes,Need Major Repair,Yes,Need Replacement,Yes,Yes,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17110219602,BOLLONGGRE GOVT. LPS,Yes,Need Store Room,Yes,Good Condition,Yes,Yes,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17110101001,CHIGITCHAKGRE GOVT. LPS,Yes,Need Major Repair,Yes,Need Replacement,Yes,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# STEP 2.9: Load School Point Shapefile

schools_gdf = gpd.read_file("../data/raw/meghalaya/boundaries/school/schools.shp")
schools_gdf.head()

,udiseCode,villageID,Village_Na,blockID,Block_Name,districtID,District_N,schoolName,udiseCod_1,schoolType,...,schoolMobi,schoolWebs,schoolEmai,schoolFax,Latitude,Longitude,clusterCat,clusterID,clusterNam,geometry
0,1.701010e+10,170101002,RAMJONGGRI,170101,SELSELLA,1701,WEST GARO HILLS,RAMJONGGRI L.P. SCHOOL,1.701010e+10,Co-ed,...,8.414029e+09,None,sujib.paul2@gmail.com,None,25.740639,89.983667,Grouping Cluster 1699,1701010012,RAMJONGGRE CRC,POINT (89.98367 25.74064)
1,1.701010e+10,170101002,RAMJONGGRI,170101,SELSELLA,1701,WEST GARO HILLS,RAMJONGGRI UPS,1.701010e+10,Co-ed,...,8.787445e+09,None,None,None,25.741139,89.983833,Grouping Cluster 1699,1701010012,RAMJONGGRE CRC,POINT (89.98383 25.74114)
2,1.701010e+10,170101004,NENGKALPARA,170101,SELSELLA,1701,WEST GARO HILLS,NENGKALPARA GOVT. LP. SCHOOL.,1.701010e+10,Co-ed,...,9.402530e+09,None,None,None,25.680036,90.006406,Grouping Cluster 1453,1701010025,OKKANGGRE CRC,POINT (90.00641 25.68004)
3,1.701010e+10,170101004,NENGKALPARA,170101,SELSELLA,1701,WEST GARO HILLS,NENGKALPARA SSA UPS,1.701010e+10,Co-ed,...,9.366931e+09,None,None,None,25.678985,90.007890,Grouping Cluster 1453,1701010025,OKKANGGRE CRC,POINT (90.00789 25.67898)
4,1.701010e+10,170101007,ROCHONPARA,170101,SELSELLA,1701,WEST GARO HILLS,ROCHONPARA GOVT. LP. SCHOOL,1.701010e+10,Co-ed,...,6.901318e+09,None,None,None,25.648581,90.042717,Grouping Cluster 1812,1701010001,ROCHONPARA CRC,POINT (90.04272 25.64858)

In [16]:
# STEP 2.9.1: Standardize UDISE, Block, District column names

schools_gdf = schools_gdf.rename(columns={
    "udiseCode": "udise_code",
    "Block_Name": "block_name",
    "District_N": "district_name"
})

schools_gdf["udise_code"] = schools_gdf["udise_code"].astype(str)

schools_gdf.head()

,udise_code,villageID,Village_Na,blockID,block_name,districtID,district_name,schoolName,udiseCod_1,schoolType,...,schoolMobi,schoolWebs,schoolEmai,schoolFax,Latitude,Longitude,clusterCat,clusterID,clusterNam,geometry
0,17010100201.0,170101002,RAMJONGGRI,170101,SELSELLA,1701,WEST GARO HILLS,RAMJONGGRI L.P. SCHOOL,1.701010e+10,Co-ed,...,8.414029e+09,None,sujib.paul2@gmail.com,None,25.740639,89.983667,Grouping Cluster 1699,1701010012,RAMJONGGRE CRC,POINT (89.98367 25.74064)
1,17010100202.0,170101002,RAMJONGGRI,170101,SELSELLA,1701,WEST GARO HILLS,RAMJONGGRI UPS,1.701010e+10,Co-ed,...,8.787445e+09,None,None,None,25.741139,89.983833,Grouping Cluster 1699,1701010012,RAMJONGGRE CRC,POINT (89.98383 25.74114)
2,17010100401.0,170101004,NENGKALPARA,170101,SELSELLA,1701,WEST GARO HILLS,NENGKALPARA GOVT. LP. SCHOOL.,1.701010e+10,Co-ed,...,9.402530e+09,None,None,None,25.680036,90.006406,Grouping Cluster 1453,1701010025,OKKANGGRE CRC,POINT (90.00641 25.68004)
3,17010100402.0,170101004,NENGKALPARA,170101,SELSELLA,1701,WEST GARO HILLS,NENGKALPARA SSA UPS,1.701010e+10,Co-ed,...,9.366931e+09,None,None,None,25.678985,90.007890,Grouping Cluster 1453,1701010025,OKKANGGRE CRC,POINT (90.00789 25.67898)
4,17010100701.0,170101007,ROCHONPARA,170101,SELSELLA,1701,WEST GARO HILLS,ROCHONPARA GOVT. LP. SCHOOL,1.701010e+10,Co-ed,...,6.901318e+09,None,None,None,25.648581,90.042717,Grouping Cluster 1812,1701010001,ROCHONPARA CRC,POINT (90.04272 25.64858)

In [23]:
def clean_udise(x):
    try:
        return str(int(float(x)))
    except:
        return None

school_health["udise_code"] = school_health["udise_code"].apply(clean_udise)
schools_gdf["udise_code"] = schools_gdf["udise_code"].apply(clean_udise)

# Check
schools_gdf["udise_code"].head(), school_health["udise_code"].head()

(0    17010100201
 1    17010100202
 2    17010100401
 3    17010100402
 4    17010100701
 Name: udise_code, dtype: object,
 0    17010105501
 1    17110215701
 2    17010105401
 3    17110219602
 4    17110101001
 Name: udise_code, dtype: object)

In [25]:
# STEP 2.10: Merge health indicators with school spatial layer

school_health_gdf = schools_gdf.merge(
    school_health,
    on="udise_code",
    how="left"
)

# Check result
print(school_health_gdf.shape)
school_health_gdf.head()

(11372, 73)

,udise_code,villageID,Village_Na,blockID,block_name_x,districtID,district_name_x,schoolName,udiseCod_1,schoolType,...,school_name_y,deworming_given,enrolled_girls,enrolled_boys,treated_girls,treated_boys,side_effect_girls_y,side_effect_boys_y,referred_girls_y,referred_boys_y
0,17010100201,170101002,RAMJONGGRI,170101,SELSELLA,1701,WEST GARO HILLS,RAMJONGGRI L.P. SCHOOL,1.701010e+10,Co-ed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17010100202,170101002,RAMJONGGRI,170101,SELSELLA,1701,WEST GARO HILLS,RAMJONGGRI UPS,1.701010e+10,Co-ed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17010100401,170101004,NENGKALPARA,170101,SELSELLA,1701,WEST GARO HILLS,NENGKALPARA GOVT. LP. SCHOOL.,1.701010e+10,Co-ed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17010100402,170101004,NENGKALPARA,170101,SELSELLA,1701,WEST GARO HILLS,NENGKALPARA SSA UPS,1.701010e+10,Co-ed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17010100701,170101007,ROCHONPARA,170101,SELSELLA,1701,WEST GARO HILLS,ROCHONPARA GOVT. LP. SCHOOL,1.701010e+10,Co-ed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Check available columns related to IFA and Deworming
cols = school_health_gdf.columns
[c for c in cols if "ifa" in c.lower() or "girl" in c.lower() or "boy" in c.lower() or "treated" in c.lower()]

['ifa_given',
 'total_girls',
 'total_boys',
 'consuming_girls',
 'consuming_boys',
 'side_effect_girls_x',
 'side_effect_boys_x',
 'referred_girls_x',
 'referred_boys_x',
 'district_name_ifa_pink',
 'block_name_ifa_pink',
 'ifa_given_ifa_pink',
 'total_girls_ifa_pink',
 'total_boys_ifa_pink',
 'consuming_girls_ifa_pink',
 'consuming_boys_ifa_pink',
 'side_effect_girls_ifa_pink',
 'side_effect_boys_ifa_pink',
 'referred_girls_ifa_pink',
 'referred_boys_ifa_pink',
 'enrolled_girls',
 'enrolled_boys',
 'treated_girls',
 'treated_boys',
 'side_effect_girls_y',
 'side_effect_boys_y',
 'referred_girls_y',
 'referred_boys_y']

In [29]:
# Convert required columns to numeric
num_cols = [
    "total_girls", "total_boys",
    "consuming_girls", "consuming_boys",
    "enrolled_girls", "enrolled_boys",
    "treated_girls", "treated_boys"
]

for col in num_cols:
    school_health_gdf[col] = pd.to_numeric(school_health_gdf[col], errors="coerce")

In [30]:
# STEP 2.11: Compute coverage indicators

school_health_gdf["ifa_coverage_girls"] = (
    school_health_gdf["consuming_girls"] / school_health_gdf["total_girls"]
)

school_health_gdf["ifa_coverage_boys"] = (
    school_health_gdf["consuming_boys"] / school_health_gdf["total_boys"]
)

school_health_gdf["deworm_coverage_girls"] = (
    school_health_gdf["treated_girls"] / school_health_gdf["enrolled_girls"]
)

school_health_gdf["deworm_coverage_boys"] = (
    school_health_gdf["treated_boys"] / school_health_gdf["enrolled_boys"]
)

school_health_gdf[
    ["ifa_coverage_girls", "ifa_coverage_boys",
     "deworm_coverage_girls", "deworm_coverage_boys"]
].head()

,ifa_coverage_girls,ifa_coverage_boys,deworm_coverage_girls,deworm_coverage_boys
0,NaN,NaN,NaN,NaN
1,1.0,1.0,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN

In [31]:
school_health_gdf.columns

Index(['udise_code', 'villageID', 'Village_Na', 'blockID', 'block_name_x',
       'districtID', 'district_name_x', 'schoolName', 'udiseCod_1',
       'schoolType', 'schoolcato', 'classFrom', 'classTo', 'Status',
       'location', 'schoolPinc', 'curriculum', 'PrincipalN', 'schoolPhon',
       'schoolMobi', 'schoolWebs', 'schoolEmai', 'schoolFax', 'Latitude',
       'Longitude', 'clusterCat', 'clusterID', 'clusterNam', 'geometry',
       'school_name_x', 'kitchen_shed', 'kitchen_shed_condition',
       'kitchen_device', 'kitchen_device_condition', 'food_grain',
       'no_of_cooks', 'fencing', 'handwash', 'drinking_water',
       'students_without_aadhaar', 'students_with_aadhaar', 'district_name_y',
       'block_name_y', 'ifa_given', 'total_girls', 'total_boys',
       'consuming_girls', 'consuming_boys', 'side_effect_girls_x',
       'side_effect_boys_x', 'referred_girls_x', 'referred_boys_x',
       'district_name_ifa_pink', 'block_name_ifa_pink', 'ifa_given_ifa_pink',
       'total_girls_ifa_pink', 'total_boys_ifa_pink',
       'consuming_girls_ifa_pink', 'consuming_boys_ifa_pink',
       'side_effect_girls_ifa_pink', 'side_effect_boys_ifa_pink',
       'referred_girls_ifa_pink', 'referred_boys_ifa_pink', 'school_name_y',
       'deworming_given', 'enrolled_girls', 'enrolled_boys', 'treated_girls',
       'treated_boys', 'side_effect_girls_y', 'side_effect_boys_y',
       'referred_girls_y', 'referred_boys_y', 'ifa_coverage_girls',
       'ifa_coverage_boys', 'deworm_coverage_girls', 'deworm_coverage_boys'],
      dtype='object')

In [32]:
# STEP 2.12: Block-wise health aggregation

block_health = school_health_gdf.groupby("block_name_x").agg({
    "ifa_coverage_girls": "mean",
    "ifa_coverage_boys": "mean",
    "deworm_coverage_girls": "mean",
    "deworm_coverage_boys": "mean"
}).reset_index()

block_health.columns = [
    "block_name",
    "avg_ifa_coverage_girls",
    "avg_ifa_coverage_boys",
    "avg_deworm_coverage_girls",
    "avg_deworm_coverage_boys"
]

block_health.head()

,block_name,avg_ifa_coverage_girls,avg_ifa_coverage_boys,avg_deworm_coverage_girls,avg_deworm_coverage_boys
0,AMLAREM,NaN,NaN,NaN,NaN
1,BAGHMARA,NaN,NaN,1.000000,1.0
2,BAJENGDOBA,NaN,NaN,0.699115,1.0
3,BETASING,2.5,2.5,NaN,NaN
4,BHOIRYMBONG,NaN,NaN,NaN,NaN

In [35]:
# STEP 2.13.0: Load block boundary shapefile

blocks_shape = gpd.read_file("../data/raw/meghalaya/boundaries/block/block.shp")

# Standardize column names
blocks_shape = blocks_shape.rename(columns={
    "block": "block_name",
    "district": "district_name"
})

blocks_shape.head()

,district_name,block_name,length,area_sqkm,area_ha,geometry
0,Ri Bhoi,Jirang,245992.302974,663.784610,66378.460998,"POLYGON ((91.79591 25.83289, 91.79484 25.83246..."
1,Ri Bhoi,Umsning,243348.566830,672.672467,67267.246705,"POLYGON ((92.16248 25.82693, 92.16243 25.82695..."
2,Ri Bhoi,Umling,174192.987300,705.096018,70509.601839,"POLYGON ((92.13274 26.04485, 92.13316 26.04456..."
3,East Jaintia Hills,Saipung,206436.144271,1071.902761,107190.276136,"POLYGON ((92.52237 25.13952, 92.52237 25.13959..."
4,East Jaintia Hills,Khliehriat,218166.350734,971.285079,97128.507887,"POLYGON ((92.405 25.44682, 92.40488 25.4466, 9..."

In [36]:
# STEP 2.13: Join health metrics with block boundaries

block_health_gdf = blocks_shape.merge(
    block_health,
    on="block_name",
    how="left"
)

block_health_gdf.head()

,district_name,block_name,length,area_sqkm,area_ha,geometry,avg_ifa_coverage_girls,avg_ifa_coverage_boys,avg_deworm_coverage_girls,avg_deworm_coverage_boys
0,Ri Bhoi,Jirang,245992.302974,663.784610,66378.460998,"POLYGON ((91.79591 25.83289, 91.79484 25.83246...",NaN,NaN,NaN,NaN
1,Ri Bhoi,Umsning,243348.566830,672.672467,67267.246705,"POLYGON ((92.16248 25.82693, 92.16243 25.82695...",NaN,NaN,NaN,NaN
2,Ri Bhoi,Umling,174192.987300,705.096018,70509.601839,"POLYGON ((92.13274 26.04485, 92.13316 26.04456...",NaN,NaN,NaN,NaN
3,East Jaintia Hills,Saipung,206436.144271,1071.902761,107190.276136,"POLYGON ((92.52237 25.13952, 92.52237 25.13959...",NaN,NaN,NaN,NaN
4,East Jaintia Hills,Khliehriat,218166.350734,971.285079,97128.507887,"POLYGON ((92.405 25.44682, 92.40488 25.4466, 9...",NaN,NaN,NaN,NaN

In [37]:
# STEP 2.14: Save block-level health intelligence layer

block_health_gdf.to_file(
    "../data/processed/meghalaya/block_health_intelligence.geojson",
    driver="GeoJSON"
)

In [38]:
import os
os.path.exists("../data/processed/meghalaya/block_health_intelligence.geojson")

True

In [39]:
# STEP 3.1: Create Meghalaya state boundary from district shapefile

import geopandas as gpd

districts_shape = gpd.read_file("../data/raw/meghalaya/boundaries/district/district.shp")

# Dissolve all districts into one state polygon
state_shape = districts_shape.dissolve()

# Check result
state_shape.head(), state_shape.crs

(                                            geometry        id  \
 0  POLYGON ((90.96928 25.17294, 90.96871 25.17253...  17273285

               name
 0  East Garo Hills  ,
 <Geographic 2D CRS: EPSG:4326>
 Name: WGS 84
 Axis Info [ellipsoidal]:
 - Lat[north]: Geodetic latitude (degree)
 - Lon[east]: Geodetic longitude (degree)
 Area of Use:
 - name: World.
 - bounds: (-180.0, -90.0, 180.0, 90.0)
 Datum: World Geodetic System 1984 ensemble
 - Ellipsoid: WGS 84
 - Prime Meridian: Greenwich)

In [40]:
# STEP 3.2: Download Meghalaya road network from OpenStreetMap

import osmnx as ox

# Use the state boundary polygon
meghalaya_polygon = state_shape.geometry.iloc[0]

# Download all drivable roads
G = ox.graph_from_polygon(meghalaya_polygon, network_type="drive")

# Convert to GeoDataFrame (edges = road segments)
roads_gdf = ox.graph_to_gdfs(G, nodes=False)

# Inspect
roads_gdf.head(), roads_gdf.crs

C:\ROSH\DeepSpatial\geospatial-infra-llm\venv\lib\site-packages\osmnx\_overpass.py:271: UserWarning: This area is 11 times your configured Overpass max query area size. It will automatically be divided up into multiple sub-queries accordingly. This may take a long time.
  multi_poly_proj = utils_geo._consolidate_subdivide_geometry(poly_proj)

(                               osmid      highway  ref  oneway reversed  \
 u         v          key
 568988751 9713971604 0     850774527        trunk  NH6   False     True
           9714006887 0     888735862     tertiary  NaN   False     True
 568988781 9714006922 0     666960671        trunk  NH6   False    False
           6960190526 0     666960671        trunk  NH6   False     True
           9714006902 0    1057187982  residential  NaN   False    False

                                length  \
 u         v          key
 568988751 9713971604 0      12.616287
           9714006887 0     279.599761
 568988781 9714006922 0     591.526998
           6960190526 0    1323.618745
           9714006902 0     150.087374

                                                                    geometry  \
 u         v          key
 568988751 9713971604 0    LINESTRING (92.43496 25.03505, 92.43503 25.035...
           9714006887 0    LINESTRING (92.43496 25.03505, 92.43492 25.035...
 568988781 9714006922 0    LINESTRING (92.41741 25.04237, 92.41748 25.042...
           6960190526 0    LINESTRING (92.41741 25.04237, 92.41732 25.042...
           9714006902 0    LINESTRING (92.41741 25.04237, 92.41764 25.042...

                          bridge name maxspeed lanes tunnel access junction  \
 u         v          key
 568988751 9713971604 0      NaN  NaN      NaN   NaN    NaN    NaN      NaN
           9714006887 0      NaN  NaN      NaN   NaN    NaN    NaN      NaN
 568988781 9714006922 0      NaN  NaN      NaN   NaN    NaN    NaN      NaN
           6960190526 0      NaN  NaN      NaN   NaN    NaN    NaN      NaN
           9714006902 0      NaN  NaN      NaN   NaN    NaN    NaN      NaN

                          width
 u         v          key
 568988751 9713971604 0     NaN
           9714006887 0     NaN
 568988781 9714006922 0     NaN
           6960190526 0     NaN
           9714006902 0     NaN  ,
 <Geographic 2D CRS: EPSG:4326>
 Name: WGS 84
 Axis Info [ellipsoidal]:
 - Lat[north]: Geodetic latitude (degree)
 - Lon[east]: Geodetic longitude (degree)
 Area of Use:
 - name: World.
 - bounds: (-180.0, -90.0, 180.0, 90.0)
 Datum: World Geodetic System 1984 ensemble
 - Ellipsoid: WGS 84
 - Prime Meridian: Greenwich)

In [41]:
# STEP 3.3: Convert road network graph to GeoDataFrame
edges = ox.graph_to_gdfs(G, nodes=False, edges=True)
edges = edges.reset_index()

# Keep only required columns
roads_gdf = edges[["geometry", "highway", "length"]].copy()
roads_gdf.crs = "EPSG:4326"

roads_gdf.head(), roads_gdf.shape

(                                            geometry      highway       length
 0  LINESTRING (92.43496 25.03505, 92.43503 25.035...        trunk    12.616287
 1  LINESTRING (92.43496 25.03505, 92.43492 25.035...     tertiary   279.599761
 2  LINESTRING (92.41741 25.04237, 92.41748 25.042...        trunk   591.526998
 3  LINESTRING (92.41741 25.04237, 92.41732 25.042...        trunk  1323.618745
 4  LINESTRING (92.41741 25.04237, 92.41764 25.042...  residential   150.087374,
 (67407, 3))

In [42]:
# STEP 3.4: Reproject both layers to metric CRS for accurate length (meters)
blocks_proj = blocks_shape.to_crs(epsg=32646)   # UTM zone for Meghalaya
roads_proj = roads_gdf.to_crs(epsg=32646)

# Spatial join: assign each road segment to a block
roads_with_blocks = gpd.sjoin(roads_proj, blocks_proj, how="left", predicate="intersects")

roads_with_blocks.head(), roads_with_blocks.shape

(                                            geometry      highway  \
 0  LINESTRING (442997.466 2768948.005, 443004.364...        trunk
 1  LINESTRING (442997.466 2768948.005, 442993.392...     tertiary
 2  LINESTRING (441230.738 2769766.227, 441237.315...        trunk
 3  LINESTRING (441230.738 2769766.227, 441221.173...        trunk
 4  LINESTRING (441230.738 2769766.227, 441253.315...  residential

    length_left  index_right       district_name  block_name   length_right  \
 0    12.616287          NaN                 NaN         NaN            NaN
 1   279.599761          4.0  East Jaintia Hills  Khliehriat  218166.350734
 2   591.526998          4.0  East Jaintia Hills  Khliehriat  218166.350734
 3  1323.618745          4.0  East Jaintia Hills  Khliehriat  218166.350734
 4   150.087374          4.0  East Jaintia Hills  Khliehriat  218166.350734

     area_sqkm       area_ha
 0         NaN           NaN
 1  971.285079  97128.507887
 2  971.285079  97128.507887
 3  971.285079  97128.507887
 4  971.285079  97128.507887  ,
 (68451, 9))

In [43]:
# STEP 3.5: Drop roads not matched to any block
roads_with_blocks_clean = roads_with_blocks.dropna(subset=["block_name"])

# Convert length from meters to kilometers
roads_with_blocks_clean["length_km"] = roads_with_blocks_clean.geometry.length / 1000

# Aggregate total road length per block
block_road_stats = roads_with_blocks_clean.groupby("block_name").agg(
    total_road_km=("length_km", "sum"),
    block_area_sqkm=("area_sqkm", "first")
).reset_index()

# Compute road density (km of road per sq km of area)
block_road_stats["road_density_km_per_sqkm"] = (
    block_road_stats["total_road_km"] / block_road_stats["block_area_sqkm"]
)

block_road_stats.head()

C:\ROSH\DeepSpatial\geospatial-infra-llm\venv\lib\site-packages\geopandas\geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

    block_name  total_road_km  block_area_sqkm  road_density_km_per_sqkm
0      Amlarem     434.655710       446.841876                  0.972728
1     Baghmara     284.443509       472.323203                  0.602222
2   Bajengdoba     102.809056       334.583072                  0.307275
3     Betasing     237.649114       171.162743                  1.388440
4  Bhoirymbong     464.594642       328.350664                  1.414934

In [44]:
# STEP 3.6: Join road stats with block geometries

block_infra_gdf = blocks_shape.merge(
    block_road_stats,
    on="block_name",
    how="left"
)

block_infra_gdf.head()

,district_name,block_name,length,area_sqkm,area_ha,geometry,total_road_km,block_area_sqkm,road_density_km_per_sqkm
0,Ri Bhoi,Jirang,245992.302974,663.784610,66378.460998,"POLYGON ((91.79591 25.83289, 91.79484 25.83246...",168.028044,663.784610,0.253136
1,Ri Bhoi,Umsning,243348.566830,672.672467,67267.246705,"POLYGON ((92.16248 25.82693, 92.16243 25.82695...",507.813252,672.672467,0.754919
2,Ri Bhoi,Umling,174192.987300,705.096018,70509.601839,"POLYGON ((92.13274 26.04485, 92.13316 26.04456...",561.854259,705.096018,0.796848
3,East Jaintia Hills,Saipung,206436.144271,1071.902761,107190.276136,"POLYGON ((92.52237 25.13952, 92.52237 25.13959...",254.227885,1071.902761,0.237174
4,East Jaintia Hills,Khliehriat,218166.350734,971.285079,97128.507887,"POLYGON ((92.405 25.44682, 92.40488 25.4466, 9...",747.458795,971.285079,0.769557

In [46]:
# Standardize block names to uppercase in both tables
schools_gdf["block_name"] = schools_gdf["block_name"].str.upper()
blocks_shape["block_name"] = blocks_shape["block_name"].str.upper()

# Recompute school counts
school_counts = schools_gdf.groupby("block_name").size().reset_index(name="total_schools")

# Merge with block areas
school_density = school_counts.merge(
    blocks_shape[["block_name", "area_sqkm"]],
    on="block_name",
    how="left"
)

# Compute density
school_density["schools_per_sqkm"] = school_density["total_schools"] / school_density["area_sqkm"]

school_density.head()

    block_name  total_schools   area_sqkm  schools_per_sqkm
0      AMLAREM            181  446.841876          0.405065
1     BAGHMARA            274  472.323203          0.580111
2   BAJENGDOBA            251  334.583072          0.750187
3     BETASING            212  171.162743          1.238587
4  BHOIRYMBONG            194  328.350664          0.590832

In [51]:
road_density = block_road_stats[[
    "block_name",
    "total_road_km",
    "block_area_sqkm",
    "road_density_km_per_sqkm"
]]

road_density.head()

    block_name  total_road_km  block_area_sqkm  road_density_km_per_sqkm
0      Amlarem     434.655710       446.841876                  0.972728
1     Baghmara     284.443509       472.323203                  0.602222
2   Bajengdoba     102.809056       334.583072                  0.307275
3     Betasing     237.649114       171.162743                  1.388440
4  Bhoirymbong     464.594642       328.350664                  1.414934

In [53]:
road_density["block_name"] = road_density["block_name"].str.upper()
school_density["block_name"] = school_density["block_name"].str.upper()

infra_intelligence = road_density.merge(
    school_density,
    on="block_name",
    how="left"
)

infra_intelligence.head()

,block_name,total_road_km,block_area_sqkm,road_density_km_per_sqkm,total_schools,area_sqkm,schools_per_sqkm
0,AMLAREM,434.655710,446.841876,0.972728,181.0,446.841876,0.405065
1,BAGHMARA,284.443509,472.323203,0.602222,274.0,472.323203,0.580111
2,BAJENGDOBA,102.809056,334.583072,0.307275,251.0,334.583072,0.750187
3,BETASING,237.649114,171.162743,1.388440,212.0,171.162743,1.238587
4,BHOIRYMBONG,464.594642,328.350664,1.414934,194.0,328.350664,0.590832

In [54]:
# Ensure same case for joining
blocks_shape["block_name"] = blocks_shape["block_name"].str.upper()

block_infra_gdf = blocks_shape.merge(
    infra_intelligence,
    on="block_name",
    how="left"
)

block_infra_gdf.head()

,district_name,block_name,length,area_sqkm_x,area_ha,geometry,total_road_km,block_area_sqkm,road_density_km_per_sqkm,total_schools,area_sqkm_y,schools_per_sqkm
0,Ri Bhoi,JIRANG,245992.302974,663.784610,66378.460998,"POLYGON ((91.79591 25.83289, 91.79484 25.83246...",168.028044,663.784610,0.253136,146.0,663.784610,0.219951
1,Ri Bhoi,UMSNING,243348.566830,672.672467,67267.246705,"POLYGON ((92.16248 25.82693, 92.16243 25.82695...",507.813252,672.672467,0.754919,253.0,672.672467,0.376112
2,Ri Bhoi,UMLING,174192.987300,705.096018,70509.601839,"POLYGON ((92.13274 26.04485, 92.13316 26.04456...",561.854259,705.096018,0.796848,331.0,705.096018,0.469440
3,East Jaintia Hills,SAIPUNG,206436.144271,1071.902761,107190.276136,"POLYGON ((92.52237 25.13952, 92.52237 25.13959...",254.227885,1071.902761,0.237174,200.0,1071.902761,0.186584
4,East Jaintia Hills,KHLIEHRIAT,218166.350734,971.285079,97128.507887,"POLYGON ((92.405 25.44682, 92.40488 25.4466, 9...",747.458795,971.285079,0.769557,374.0,971.285079,0.385057

In [57]:
block_infra_gdf.to_file(
    "../data/processed/meghalaya/block_infrastructure_intelligence.geojson",
    driver="GeoJSON"
)

print("Block infrastructure intelligence layer saved successfully.")

Block infrastructure intelligence layer saved successfully.

In [59]:
import os

os.listdir("../data/processed/meghalaya")

['blocks_final.geojson',
 'block_health_intelligence.geojson',
 'block_infrastructure_intelligence.geojson']

In [60]:
import geopandas as gpd

block_health_gdf = gpd.read_file("../data/processed/meghalaya/block_health_intelligence.geojson")
block_infra_gdf = gpd.read_file("../data/processed/meghalaya/block_infrastructure_intelligence.geojson")

block_health_gdf.shape, block_infra_gdf.shape

((46, 10), (46, 12))

In [61]:
# Merge on block_name and geometry
block_intelligence = block_infra_gdf.merge(
    block_health_gdf.drop(columns="geometry"),
    on="block_name",
    how="left"
)

block_intelligence.head()

,district_name_x,block_name,length_x,area_sqkm_x,area_ha_x,total_road_km,block_area_sqkm,road_density_km_per_sqkm,total_schools,area_sqkm_y,schools_per_sqkm,geometry,district_name_y,length_y,area_sqkm,area_ha_y,avg_ifa_coverage_girls,avg_ifa_coverage_boys,avg_deworm_coverage_girls,avg_deworm_coverage_boys
0,Ri Bhoi,JIRANG,245992.302974,663.784610,66378.460998,168.028044,663.784610,0.253136,146.0,663.784610,0.219951,"POLYGON ((91.79591 25.83289, 91.79484 25.83246...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ri Bhoi,UMSNING,243348.566830,672.672467,67267.246705,507.813252,672.672467,0.754919,253.0,672.672467,0.376112,"POLYGON ((92.16248 25.82693, 92.16243 25.82695...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ri Bhoi,UMLING,174192.987300,705.096018,70509.601839,561.854259,705.096018,0.796848,331.0,705.096018,0.469440,"POLYGON ((92.13274 26.04485, 92.13316 26.04456...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,East Jaintia Hills,SAIPUNG,206436.144271,1071.902761,107190.276136,254.227885,1071.902761,0.237174,200.0,1071.902761,0.186584,"POLYGON ((92.52237 25.13952, 92.52237 25.13959...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,East Jaintia Hills,KHLIEHRIAT,218166.350734,971.285079,97128.507887,747.458795,971.285079,0.769557,374.0,971.285079,0.385057,"POLYGON ((92.405 25.44682, 92.40488 25.4466, 9...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
# Clean column names
block_intelligence = block_intelligence.rename(columns={
    "district_name_x": "district_name",
    "length_x": "block_boundary_length",
    "area_sqkm_x": "block_area_sqkm",
    "area_ha_x": "block_area_ha"
})

# Keep only required columns
block_intelligence_final = block_intelligence[[
    "district_name",
    "block_name",
    "block_area_sqkm",
    "total_road_km",
    "road_density_km_per_sqkm",
    "total_schools",
    "schools_per_sqkm",
    "avg_ifa_coverage_girls",
    "avg_ifa_coverage_boys",
    "avg_deworm_coverage_girls",
    "avg_deworm_coverage_boys",
    "geometry"
]]

block_intelligence_final.head()

,district_name,block_name,block_area_sqkm,block_area_sqkm,total_road_km,road_density_km_per_sqkm,total_schools,schools_per_sqkm,avg_ifa_coverage_girls,avg_ifa_coverage_boys,avg_deworm_coverage_girls,avg_deworm_coverage_boys,geometry
0,Ri Bhoi,JIRANG,663.784610,663.784610,168.028044,0.253136,146.0,0.219951,NaN,NaN,NaN,NaN,"POLYGON ((91.79591 25.83289, 91.79484 25.83246..."
1,Ri Bhoi,UMSNING,672.672467,672.672467,507.813252,0.754919,253.0,0.376112,NaN,NaN,NaN,NaN,"POLYGON ((92.16248 25.82693, 92.16243 25.82695..."
2,Ri Bhoi,UMLING,705.096018,705.096018,561.854259,0.796848,331.0,0.469440,NaN,NaN,NaN,NaN,"POLYGON ((92.13274 26.04485, 92.13316 26.04456..."
3,East Jaintia Hills,SAIPUNG,1071.902761,1071.902761,254.227885,0.237174,200.0,0.186584,NaN,NaN,NaN,NaN,"POLYGON ((92.52237 25.13952, 92.52237 25.13959..."
4,East Jaintia Hills,KHLIEHRIAT,971.285079,971.285079,747.458795,0.769557,374.0,0.385057,NaN,NaN,NaN,NaN,"POLYGON ((92.405 25.44682, 92.40488 25.4466, 9..."

In [63]:
# Remove duplicate block_area_sqkm column
block_intelligence_final = block_intelligence_final.loc[:,~block_intelligence_final.columns.duplicated()]

block_intelligence_final.head()

,district_name,block_name,block_area_sqkm,total_road_km,road_density_km_per_sqkm,total_schools,schools_per_sqkm,avg_ifa_coverage_girls,avg_ifa_coverage_boys,avg_deworm_coverage_girls,avg_deworm_coverage_boys,geometry
0,Ri Bhoi,JIRANG,663.784610,168.028044,0.253136,146.0,0.219951,NaN,NaN,NaN,NaN,"POLYGON ((91.79591 25.83289, 91.79484 25.83246..."
1,Ri Bhoi,UMSNING,672.672467,507.813252,0.754919,253.0,0.376112,NaN,NaN,NaN,NaN,"POLYGON ((92.16248 25.82693, 92.16243 25.82695..."
2,Ri Bhoi,UMLING,705.096018,561.854259,0.796848,331.0,0.469440,NaN,NaN,NaN,NaN,"POLYGON ((92.13274 26.04485, 92.13316 26.04456..."
3,East Jaintia Hills,SAIPUNG,1071.902761,254.227885,0.237174,200.0,0.186584,NaN,NaN,NaN,NaN,"POLYGON ((92.52237 25.13952, 92.52237 25.13959..."
4,East Jaintia Hills,KHLIEHRIAT,971.285079,747.458795,0.769557,374.0,0.385057,NaN,NaN,NaN,NaN,"POLYGON ((92.405 25.44682, 92.40488 25.4466, 9..."

In [64]:
block_intelligence_final.to_file(
    "../data/processed/meghalaya/infra_health_master.gpkg",
    layer="block_intelligence",
    driver="GPKG"
)

print("Meghalaya Block-level Infra + Health Intelligence saved successfully.")

Meghalaya Block-level Infra + Health Intelligence saved successfully.

In [70]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:7654@localhost:5433/meghalaya_geo_llm")

with engine.connect() as conn:
    print("PostGIS connected successfully!")

PostGIS connected successfully!

In [71]:
import geopandas as gpd

gdf = gpd.read_file("../data/processed/meghalaya/infra_health_master.gpkg", layer="block_intelligence")

gdf.to_postgis(
    "meghalaya_block_intelligence",
    engine,
    if_exists="replace",
    index=False
)

print("Meghalaya Block Intelligence loaded into PostGIS.")

Meghalaya Block Intelligence loaded into PostGIS.

In [74]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:7654@localhost:5433/meghalaya_geo_llm")

df = pd.read_sql("SELECT block_name, road_density_km_per_sqkm, avg_ifa_coverage_girls FROM meghalaya_block_intelligence LIMIT 5;", engine)
df

   block_name  road_density_km_per_sqkm avg_ifa_coverage_girls
0      JIRANG                  0.253136                   None
1     UMSNING                  0.754919                   None
2      UMLING                  0.796848                   None
3     SAIPUNG                  0.237174                   None
4  KHLIEHRIAT                  0.769557                   None

In [75]:
schema_description = """
Table: meghalaya_block_intelligence

Columns:
- block_name (text)
- district_name (text)
- block_area_sqkm (float)
- total_road_km (float)
- road_density_km_per_sqkm (float)
- total_schools (int)
- schools_per_sqkm (float)
- avg_ifa_coverage_girls (float)
- avg_ifa_coverage_boys (float)
- avg_deworm_coverage_girls (float)
- avg_deworm_coverage_boys (float)
- geometry (Polygon, SRID 4326)
"""

In [76]:
def build_sql_prompt(question):
    return f"""
You are a geospatial SQL expert.

Database schema:
{schema_description}

Task:
Convert the following question into a valid PostgreSQL + PostGIS SQL query.

Question:
{question}

Rules:
- Use table: meghalaya_block_intelligence
- Do not hallucinate columns
- Return only SQL
"""

In [77]:
test_sql = """
SELECT block_name, road_density_km_per_sqkm, schools_per_sqkm
FROM meghalaya_block_intelligence
ORDER BY road_density_km_per_sqkm ASC
LIMIT 5;
"""

pd.read_sql(test_sql, engine)

   block_name  road_density_km_per_sqkm  schools_per_sqkm
0  TIKRIKILLA                  0.096656          0.784697
1   KHARKUTTA                  0.147182          0.611841
2  MAWSHYNRUT                  0.215897          0.247306
3     SAIPUNG                  0.237174          0.186584
4      JIRANG                  0.253136          0.219951

In [82]:
import requests

url = "http://localhost:11434/api/generate"

payload = {
    "model": "mistral",
    "prompt": "Explain in simple words what road density and school density mean for planning.",
    "stream": False
}

response = requests.post(url, json=payload)
print(response.json()["response"])

 Road Density: Road density refers to the total length of roads in a specific area divided by the area itself. In urban planning, it helps understand how well a city's infrastructure is connected, traffic flow, and accessibility of different parts of the city. High road density could indicate congested streets, while low road density might suggest underdeveloped areas.

School Density: School density refers to the number of schools present in a particular area compared to its size. It helps planners determine the educational resources available within a community and ensures that there is an equitable distribution of schools across different neighborhoods. High school density could mean overcrowded schools, while low school density might indicate areas with insufficient educational facilities.

In [83]:
def geo_prompt(user_question):
    return f"""
You are a geospatial planning expert.
We have a PostGIS table: meghalaya_block_intelligence

Columns:
- block_name
- district_name
- road_density_km_per_sqkm
- schools_per_sqkm
- avg_ifa_coverage_girls
- avg_ifa_coverage_boys
- avg_deworm_coverage_girls
- avg_deworm_coverage_boys

User Question:
{user_question}

Generate SQL to answer it.
"""

In [84]:
def ask_llm(question):
    prompt = geo_prompt(question)
    r = requests.post("http://localhost:11434/api/generate", json={
        "model": "mistral",
        "prompt": prompt,
        "stream": False
    })
    return r.json()["response"]

sql = ask_llm("Which blocks have low road density but high school density?")
print(sql)

 To find the blocks with low road density but high school density, we can use a SQL query that calculates a threshold for road density and filters the data based on that threshold while also checking for a sufficient school density. Here is an example of such a query:

```sql
WITH thresholds AS (
    SELECT
        percentile_cont(0.25) WITHIN GROUP (ORDER BY road_density_km_per_sqkm) AS low_road_threshold,
        percentile_cont(0.75) WITHIN GROUP (ORDER BY schools_per_sqkm) AS high_schools_threshold
    FROM meghalaya_block_intelligence
),
filtered_blocks AS (
    SELECT *
    FROM meghalaya_block_intelligence
    WHERE road_density_km_per_sqkm < (SELECT low_road_threshold FROM thresholds)
        AND schools_per_sqkm >= (SELECT high_schools_threshold FROM thresholds)
)
SELECT block_name, district_name, road_density_km_per_sqkm, schools_per_sqkm
FROM filtered_blocks;
```

This query first calculates the 25th percentile of road density and the 75th percentile of school density using the `PERCENTILE_CONT()` function. Then it creates a temporary view with blocks that have low road density (less than the calculated threshold) and high school density (equal to or greater than the calculated threshold). Finally, it selects and returns the necessary columns for those filtered blocks.

In [86]:
import psycopg2
import pandas as pd

conn = psycopg2.connect(
    dbname="meghalaya_geo_llm",
    user="postgres",
    password="7654",
    host="localhost",
    port="5433"
)

test = pd.read_sql("SELECT COUNT(*) FROM meghalaya_block_intelligence;", conn)
test

C:\Users\rosha\AppData\Local\Temp\ipykernel_13404\2288832694.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  test = pd.read_sql("SELECT COUNT(*) FROM meghalaya_block_intelligence;", conn)

   count
0     46

In [87]:
query = """
WITH thresholds AS (
    SELECT
        percentile_cont(0.25) WITHIN GROUP (ORDER BY road_density_km_per_sqkm) AS low_road_threshold,
        percentile_cont(0.75) WITHIN GROUP (ORDER BY schools_per_sqkm) AS high_schools_threshold
    FROM meghalaya_block_intelligence
),
filtered_blocks AS (
    SELECT *
    FROM meghalaya_block_intelligence
    WHERE road_density_km_per_sqkm < (SELECT low_road_threshold FROM thresholds)
      AND schools_per_sqkm >= (SELECT high_schools_threshold FROM thresholds)
)
SELECT block_name, district_name, road_density_km_per_sqkm, schools_per_sqkm
FROM filtered_blocks
ORDER BY road_density_km_per_sqkm ASC;
"""

result_df = pd.read_sql(query, conn)
result_df

C:\Users\rosha\AppData\Local\Temp\ipykernel_13404\202139708.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result_df = pd.read_sql(query, conn)

   block_name     district_name  road_density_km_per_sqkm  schools_per_sqkm
0  TIKRIKILLA   West Garo Hills                  0.096656          0.784697
1  BAJENGDOBA  North Garo Hills                  0.307275          0.750187

In [88]:
context = result_df.to_string(index=False)

prompt = f"""
You are a geospatial planning expert.

Below is block-level intelligence from Meghalaya showing:
- Road Density (km per sq km)
- School Density (schools per sq km)

{context}

Explain in simple planning language:
1. What problem these blocks face
2. Why they are priority infrastructure zones
3. What government actions should be taken
"""

print(prompt)

You are a geospatial planning expert.

Below is block-level intelligence from Meghalaya showing:
- Road Density (km per sq km)
- School Density (schools per sq km)

block_name    district_name  road_density_km_per_sqkm  schools_per_sqkm
TIKRIKILLA  West Garo Hills                  0.096656          0.784697
BAJENGDOBA North Garo Hills                  0.307275          0.750187

Explain in simple planning language:
1. What problem these blocks face
2. Why they are priority infrastructure zones
3. What government actions should be taken

In [105]:
import subprocess

OLLAMA_PATH = r"C:\Users\rosha\AppData\Local\Programs\Ollama\ollama.exe"

def call_ollama(prompt, model="mistral"):
    cmd = [OLLAMA_PATH, "run", model]
    p = subprocess.Popen(
        cmd,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        encoding="utf-8",
        errors="ignore"
    )
    out, err = p.communicate(prompt)
    return out.strip()

In [106]:
print(call_ollama("Say hello in one word"))

Hello!

In [107]:
def nl_to_sql(question):
    prompt = f"""
You are a PostGIS SQL expert.

Table: meghalaya_block_intelligence
Columns:
- block_name
- district_name
- road_density_km_per_sqkm
- schools_per_sqkm
- geometry

Convert the following natural language question into a valid SQL query only.

Question: {question}
SQL:
"""
    return call_ollama(prompt)

In [108]:
sql = nl_to_sql("Which blocks have low road density?")
print(sql)

To find the blocks with low road density, we can use a SQL query that filters rows where the road density is less than a certain threshold. However, since the definition of "low" might vary, I'll provide you with two examples - one for identifying blocks with the lowest road densities and another for a more general case.

1. To find the blocks with the lowest road densities:

```sql
SELECT block_name, district_name, road_density_km_per_sqkm
FROM meghalaya_block_intelligence
ORDER BY road_density_km_per_sqkm ASC
LIMIT 10; -- Modify the number in 'LIMIT' based on how many results you want to return.
```

2. To find blocks with low road density (e.g., less than 0.1 km per sqkm):

```sql
SELECT block_name, district_name, road_density_km_per_sqkm
FROM meghalaya_block_intelligence
WHERE road_density_km_per_sqkm < 0.1;
```

In [109]:
import pandas as pd
import geopandas as gpd

# Load final block intelligence
gdf = gpd.read_file("../data/processed/meghalaya/infra_health_master.gpkg", layer="block_intelligence")

# Normalize metrics (0–1 scale)
gdf["road_score"] = 1 - (gdf["road_density_km_per_sqkm"] / gdf["road_density_km_per_sqkm"].max())
gdf["school_score"] = gdf["schools_per_sqkm"] / gdf["schools_per_sqkm"].max()

# Simple priority index (can be weighted later)
gdf["infra_priority_score"] = (
    0.6 * gdf["road_score"] +
    0.4 * gdf["school_score"]
)

gdf[["block_name", "infra_priority_score"]].sort_values("infra_priority_score", ascending=False).head()

     block_name  infra_priority_score
27     BETASING              0.736523
36     SELSELLA              0.725429
37   TIKRIKILLA              0.722574
23   BAJENGDOBA              0.707282
45  RESUBELPARA              0.702084

In [112]:
import geopandas as gpd

gdf = gpd.read_file("../data/processed/meghalaya/infra_health_master.gpkg", layer="block_intelligence")
print(gdf.columns)

Index(['district_name', 'block_name', 'block_area_sqkm', 'total_road_km',
       'road_density_km_per_sqkm', 'total_schools', 'schools_per_sqkm',
       'avg_ifa_coverage_girls', 'avg_ifa_coverage_boys',
       'avg_deworm_coverage_girls', 'avg_deworm_coverage_boys', 'geometry'],
      dtype='object')

In [114]:
# Fill missing health with 0 (means 0% coverage -> high priority)
health_cols = [
    "avg_ifa_coverage_girls",
    "avg_ifa_coverage_boys",
    "avg_deworm_coverage_girls",
    "avg_deworm_coverage_boys"
]

gdf[health_cols] = gdf[health_cols].fillna(0)

# Recompute components
gdf["road_priority"] = 1 - (gdf["road_density_km_per_sqkm"] / gdf["road_density_km_per_sqkm"].max())
gdf["school_pressure"] = gdf["schools_per_sqkm"] / gdf["schools_per_sqkm"].max()
gdf["health_gap"] = 1 - gdf[health_cols].mean(axis=1)

# Final composite priority score
gdf["infra_priority_score"] = (
    0.4 * gdf["road_priority"] +
    0.3 * gdf["school_pressure"] +
    0.3 * gdf["health_gap"]
)

# View top priority blocks
gdf[["block_name","infra_priority_score"]].sort_values(
    "infra_priority_score", ascending=False
).head()

C:\Users\rosha\AppData\Local\Temp\ipykernel_13404\1789660410.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  gdf[health_cols] = gdf[health_cols].fillna(0)

    block_name  infra_priority_score
27    BETASING              0.807724
36    SELSELLA              0.797037
38      MAWLAI              0.794870
37  TIKRIKILLA              0.792302
23  BAJENGDOBA              0.781641

In [116]:
priority_path = "../data/processed/meghalaya/block_priority_intelligence.gpkg"

gdf.to_file(
    priority_path,
    layer="priority_blocks",
    driver="GPKG"
)

print("Saved at:", priority_path)

Saved at: ../data/processed/meghalaya/block_priority_intelligence.gpkg

In [117]:
import os
os.path.exists("../data/processed/meghalaya/block_priority_intelligence.gpkg")

True

In [119]:
import fiona

layers = fiona.listlayers("../data/processed/meghalaya/block_priority_intelligence.gpkg")
print(layers)

['priority_blocks']

In [120]:
import geopandas as gpd
from sqlalchemy import create_engine

# Connect to PostGIS
engine = create_engine("postgresql://postgres:7654@localhost:5433/meghalaya_geo_llm")

# Load district shapefile
district_gdf = gpd.read_file("../data/raw/meghalaya/boundaries/district/district.shp")

# Check columns
print(district_gdf.columns)

# Save to PostGIS
district_gdf.to_postgis(
    "meghalaya_districts",
    engine,
    if_exists="replace",
    index=False
)

print("District layer loaded into PostGIS as table: meghalaya_districts")

Index(['id', 'name', 'geometry'], dtype='object')
District layer loaded into PostGIS as table: meghalaya_districts